### ISSUE TITLE
Error on  File "/var/lib/snips/skills/snips-app-assistant-information/venv/lib/python3.5/site-packages/snipskit/apps.py", line 88, in __init__ 

### ISSUE THREAD

**Issue by Daenara** [koenvervloesem/snips-app-assistant-information#17]
Hello,

I am just starting out with snips and thought your app (the German translation) would be a good thing to have. Sadly it doesn't work because it crashes when the snips-skill-server tries to initialize it. I installed it using sam update-assistant and during setup.sh no errors occured. First time I noticed anything wasn't working like intended was when I tried asking for the ip and sam watch detected the right intent but it timed out waiting for an answer. I do not have enough experience with snips to try and fix it myself, but I at least managed to find the log with the error in it:

```
[21:47:35.595383] INFO :snips_skill_server_lib::runner: [assistant-information][err] Traceback (most recent call last):
[21:47:35.595476] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/var/lib/snips/skills/snips-app-assistant-information/venv/lib/python3.5/site-packages/snipskit/apps.py", line 88, in __init__
[21:47:35.596401] INFO :snips_skill_server_lib::runner: [assistant-information][err]     assistant_directory = snips['snips-common']['assistant']
[21:47:35.596467] INFO :snips_skill_server_lib::runner: [assistant-information][err] KeyError: 'assistant'
[21:47:35.596492] INFO :snips_skill_server_lib::runner: [assistant-information][err]
[21:47:35.596514] INFO :snips_skill_server_lib::runner: [assistant-information][err] During handling of the above exception, another exception occurred:
[21:47:35.596536] INFO :snips_skill_server_lib::runner: [assistant-information][err]
[21:47:35.596797] INFO :snips_skill_server_lib::runner: [assistant-information][err] Traceback (most recent call last):
[21:47:35.596841] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "./action-assistant-information.py", line 23, in <module>
[21:47:35.597589] INFO :snips_skill_server_lib::runner: [assistant-information][err]     i18n = importlib.import_module('translations.' + SnipsAppMixin().assistant['language'])
[21:47:35.597664] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/var/lib/snips/skills/snips-app-assistant-information/venv/lib/python3.5/site-packages/snipskit/apps.py", line 92, in __init__
[21:47:35.598512] INFO :snips_skill_server_lib::runner: [assistant-information][err]     self.assistant = AssistantConfig()
[21:47:35.598571] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/var/lib/snips/skills/snips-app-assistant-information/venv/lib/python3.5/site-packages/snipskit/config.py", line 141, in __init__
[21:47:35.599416] INFO :snips_skill_server_lib::runner: [assistant-information][err]     UserDict.__init__(self, json.load(json_file))
[21:47:35.599476] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/usr/lib/python3.5/json/__init__.py", line 265, in load
[21:47:35.603803] INFO :snips_skill_server_lib::runner: [assistant-information][err]     return loads(fp.read(),
[21:47:35.603879] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
[21:47:35.605049] INFO :snips_skill_server_lib::runner: [assistant-information][err]     return codecs.ascii_decode(input, self.errors)[0]
[21:47:35.605116] INFO :snips_skill_server_lib::runner: [assistant-information][err] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2071: ordinal not in range(128)
[21:47:35.715398] DEBUG:snips_skill_server_lib::runner: [assistant-information][err] thread stopped
[21:47:35.715598] DEBUG:snips_skill_server_lib::runner: [assistant-information][out] thread stopped
[21:47:35.759158] WARN :snips_skill_server_lib::handler::nosandbox: child assistant-information has stopped with status `exit code: 1`
```

I hope you can help me out with this.

Daenara

**Comment by koenvervloesem** [comment]
Can you show me your /etc/snips.toml?

**Comment by Daenara** [comment]
/etc/snips.toml is still the default with everything commented out. I just installed today and it worked out of the box so I never uncommented anything.

**Comment by koenvervloesem** [comment]
It seems like the program can't decode the assistant file because of some non-ASCII characters. Could you email me ([koen@vervloesem.eu](mailto:koen@vervloesem.eu)) the zip file of your assistant? You can find this in the Snips Console if you click on **Deploy your Assistant** and then on **Download and install manually**. Then I can try this assistant and find a fix.

**Comment by Daenara** [comment]
I sent the mail out.

**Comment by koenvervloesem** [comment]
I'm sorry, I can't reproduce this bug with your assistant file. I did find another bug because the German translation of the app is incomplete, and I fixed this. Can you try reinstalling your assistant and try again if the app works?

And what version of Snips is this? You can find this in the output of `sam status`.

**Comment by philipp2310** [comment]
I‘m away for the week, will take a look tomorrow if you like

**Comment by koenvervloesem** [comment]
That would be wonderful, Philipp.

**Comment by Daenara** [comment]
I can report that it runs now. I am not sure what exactly the problem was but after I reinstalled with the new changes everything was fine. As for the version I am running, that is 0.63.2.

Thank you for your help with this and especially the fast fix and your great response times. I normally expect to wait at least a few days before I get answers on issues.

Daenara

**Comment by koenvervloesem** [comment]
Hi @Daenara, I'm glad that it works now. Feel free to reopen this issue when the problem reappears.
